package sgea.sistema.sgea.controller;

import java.util.List;
import java.util.stream.Collectors;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

import jakarta.validation.ConstraintViolationException;
import sgea.sistema.sgea.model.PreVenda;
import sgea.sistema.sgea.response.ApiResponse;
import sgea.sistema.sgea.service.PreVendaService;

@RestController
@RequestMapping("/preVenda")
public class PreVendaController {
	
	@Autowired
	private PreVendaService preVendaService;
	
	@PostMapping("/cadastrar")
	public ResponseEntity<ApiResponse> cadastrar(@RequestBody @Validated PreVenda preVenda){
		
		try {
			
			preVendaService.cadastrar(preVenda);
			ApiResponse apiResponse = new ApiResponse("Success", "Venda realizada, dirija-se ao caixa para pagamento!");
			return new ResponseEntity<>(apiResponse, HttpStatus.CREATED);
			
		} catch (ConstraintViolationException e) {
		 
			List<String> erros = e.getConstraintViolations().stream().map(violation -> violation.getMessage())
        			.collect(Collectors.toList());
			
			ApiResponse apiResponse = new ApiResponse("Error", "Erro de validação!", erros);
        	return new ResponseEntity<>(apiResponse,HttpStatus.BAD_REQUEST);
			
		} catch (Exception e) {
			 ApiResponse apiResponse = new ApiResponse("Error", e.getMessage());
	            return new ResponseEntity<>(apiResponse, HttpStatus.BAD_REQUEST);
		}
		
	}

}
